ohlcv_2h:
  db:
    postgres_conn_id: "keynum-central-pg"
    source_table: "raw_crypto_data.ohlcv_3m"
    target_table: "raw_crypto_data.ohlcv_2h"
    symbol_quote: "USDT"
    conflict_keys: ["symbol", "exchange", "timestamp"]
    lookback_days: 14
    batch_days: 14
    bucket_minutes: 120
  schedule: "1 0-23/2 * * *"
